# Generated by Django 6.0.2 on 2026-03-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ['name']},
        ),
    ]
