# Generated by Django 6.0.2 on 2026-03-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_characteristic_options_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
