# Generated by Django 6.0.2 on 2026-03-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_workshop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
